### ISSUE TITLE
IB Integrator isn't applied to imported projects

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm-eclipse#74]
Install Gradle STTS plugin for Eclipse, import all samples. Integrator is not applied.

Related #70

**Comment by badlogic** [comment]
Same when importing Maven projects obviously. We get an NPE it seems:

```
java.lang.NullPointerException
	at com.robovm.ibintegrator.xcode.XcodeProject.addEntry(XcodeProject.java:453)
	at com.robovm.ibintegrator.xcode.XcodeProject.addEntry(XcodeProject.java:438)
	at com.robovm.ibintegrator.xcode.XcodeProject.addResourceFile(XcodeProject.java:326)
	at com.robovm.ibintegrator.xcode.XcodeProject.access$1(XcodeProject.java:314)
	at com.robovm.ibintegrator.xcode.XcodeProject$Mutator.addResourceFile(XcodeProject.java:823)
	at com.robovm.ibintegrator.IBIntegrator.resourcesCreated(IBIntegrator.java:363)
	at com.robovm.ibintegrator.IBIntegrator.access$5(IBIntegrator.java:353)
	at com.robovm.ibintegrator.IBIntegrator$2$3.modify(IBIntegrator.java:156)
	at com.robovm.ibintegrator.xcode.XcodeProject.modify(XcodeProject.java:790)
	at com.robovm.ibintegrator.IBIntegrator$2.created(IBIntegrator.java:154)
	at com.robovm.ibintegrator.xcode.DirectoryWatcher.notifyCreated(DirectoryWatcher.java:121)
	at com.robovm.ibintegrator.xcode.DirectoryWatcher.watchDirectory(DirectoryWatcher.java:111)
	at com.robovm.ibintegrator.xcode.DirectoryWatcher.watchDirectory(DirectoryWatcher.java:113)
	at com.robovm.ibintegrator.xcode.DirectoryWatcher.watchDirectory(DirectoryWatcher.java:113)
	at com.robovm.ibintegrator.xcode.DirectoryWatcher.watchDirectories(DirectoryWatcher.java:82)
	at com.robovm.ibintegrator.IBIntegrator$6.modify(IBIntegrator.java:228)
	at com.robovm.ibintegrator.xcode.XcodeProject.modify(XcodeProject.java:790)
	at com.robovm.ibintegrator.IBIntegrator.setResourceFolders(IBIntegrator.java:226)
	at sun.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.robovm.eclipse.internal.ib.IBIntegratorProxy.setResourceFolders(IBIntegratorProxy.java:78)
	at org.robovm.eclipse.internal.ib.IBIntegratorManager.projectChanged(IBIntegratorManager.java:140)
	at org.robovm.eclipse.internal.ib.IBIntegratorManager.access$0(IBIntegratorManager.java:97)
	at org.robovm.eclipse.internal.ib.IBIntegratorManager$1.visit(IBIntegratorManager.java:235)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:69)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:80)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:80)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:49)
	at org.robovm.eclipse.internal.ib.IBIntegratorManager.resourceChanged(IBIntegratorManager.java:213)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:291)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:285)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:149)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:378)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1498)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:45)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
java.lang.NullPointerException
	at com.robovm.ibintegrator.xcode.XcodeProject.addEntry(XcodeProject.java:453)
	at com.robovm.ibintegrator.xcode.XcodeProject.addEntry(XcodeProject.java:438)
	at com.robovm.ibintegrator.xcode.XcodeProject.addResourceFile(XcodeProject.java:326)
	at com.robovm.ibintegrator.xcode.XcodeProject.access$1(XcodeProject.java:314)
	at com.robovm.ibintegrator.xcode.XcodeProject$Mutator.addResourceFile(XcodeProject.java:823)
	at com.robovm.ibintegrator.IBIntegrator.resourcesCreated(IBIntegrator.java:363)
	at com.robovm.ibintegrator.IBIntegrator.access$5(IBIntegrator.java:353)
	at com.robovm.ibintegrator.IBIntegrator$2$3.modify(IBIntegrator.java:156)
	at com.robovm.ibintegrator.xcode.XcodeProject.modify(XcodeProject.java:790)
	at com.robovm.ibintegrator.IBIntegrator$2.created(IBIntegrator.java:154)
	at com.robovm.ibintegrator.xcode.DirectoryWatcher.notifyCreated(DirectoryWatcher.java:121)
	at com.robovm.ibintegrator.xcode.DirectoryWatcher.watchDirectory(DirectoryWatcher.java:111)
	at com.robovm.ibintegrator.xcode.DirectoryWatcher.watchDirectory(DirectoryWatcher.java:113)
	at com.robovm.ibintegrator.xcode.DirectoryWatcher.watchDirectories(DirectoryWatcher.java:82)
	at com.robovm.ibintegrator.IBIntegrator$6.modify(IBIntegrator.java:228)
	at com.robovm.ibintegrator.xcode.XcodeProject.modify(XcodeProject.java:790)
	at com.robovm.ibintegrator.IBIntegrator.setResourceFolders(IBIntegrator.java:226)
	at sun.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.robovm.eclipse.internal.ib.IBIntegratorProxy.setResourceFolders(IBIntegratorProxy.java:78)
	at org.robovm.eclipse.internal.ib.IBIntegratorManager.projectChanged(IBIntegratorManager.java:140)
	at org.robovm.eclipse.internal.ib.IBIntegratorManager.access$0(IBIntegratorManager.java:97)
	at org.robovm.eclipse.internal.ib.IBIntegratorManager$1.visit(IBIntegratorManager.java:235)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:69)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:80)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:80)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:49)
	at org.robovm.eclipse.internal.ib.IBIntegratorManager.resourceChanged(IBIntegratorManager.java:213)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:291)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:285)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:149)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:378)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1498)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:45)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```
