### ISSUE TITLE
ConcurrentModificationException when launching Eclipse

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm-eclipse#78]
```
!MESSAGE An internal error occurred during: "RoboVM Interface Builder Integrator launcher".
!STACK 0
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
        at org.eclipse.jdt.internal.core.JavaModelManager$9.run(JavaModelManager.java:2828)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2313)
        at org.eclipse.jdt.internal.core.JavaModelManager.initializeAllContainers(JavaModelManager.java:2848)
        at org.eclipse.jdt.internal.core.JavaModelManager.getClasspathContainer(JavaModelManager.java:1932)
        at org.eclipse.jdt.core.JavaCore.initializeAfterLoad(JavaCore.java:4016)
        at org.robovm.eclipse.internal.RoboVMProjectObserver.start(RoboVMProjectObserver.java:64)
        at org.robovm.eclipse.RoboVMPlugin$3.run(RoboVMPlugin.java:205)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

https://github.com/robovm/robovm-eclipse/blob/master/ui/src/org/robovm/eclipse/internal/RoboVMProjectObserver.java#L64 

This crashes the process where IBIntegrators get attached to robovm projects. So nothing related to the IBIntegrator plugin will work.

**Comment by badlogic** [comment]
guess we need to do this in a job. never happened to me. got repro steps?

**Comment by BlueRiverInteractive** [comment]
No, not really :) I just happen to fire up my workspace in Eclipse and get the exception. I think it's heavily dependent on what plugins you have installed, what tasks are running during launch and what projects you have. 
According to eclipse Javadocs the malfunctioning method should work concurrently but still `A client may choose to call this method in a background thread early after the workspace has started so that the initialization is transparent to the user.`.

**Comment by BlueRiverInteractive** [comment]
Fixed! Thx Mario
